//! The options of `crisp3ds-dense photos` as one table: the command-line parser
//! takes its flags, kinds and defaults from here, and `listing` gives the same
//! rows as JSON for generated forms (`crisp3ds-dense run --describe`).

use serde_json::{json, Value};

/// One option. `scope` is where it belongs: `run`, `masks`, `cameras` (every
/// provider of that module), `masks:NAME` or `cameras:NAME` (one provider),
/// `tools`, `machine`, `deadlines`, `gates`. `kind` is `switch` (`--flag` /
/// `--no-flag`), `integer`, `number`, `text`, `choice`, `provider`, `path`
/// (a file), `directory`, `executable` or `path_list` (separated like `PATH`).
pub struct OptionSpec {
    pub flag: &'static str,
    pub scope: &'static str,
    pub kind: &'static str,
    /// The value used when the flag is absent, as it would be typed; `None`: no value, or one explained in `meaning`.
    pub default: Option<&'static str>,
    pub choices: &'static [&'static str],
    /// Environment variable read when the flag is absent.
    pub variable: Option<&'static str>,
    /// May be given several times.
    pub repeated: bool,
    pub meaning: &'static str,
}

pub const OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        flag: "photos",
        scope: "run",
        kind: "directory",
        default: None,
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Folder with one photo per turntable position, named in capture order (PNG or JPEG)",
    },
    OptionSpec {
        flag: "calibration",
        scope: "run",
        kind: "path",
        default: None,
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Lens file: focal length, principal point and radial distortion (not needed with --cameras import or --stop-after masks)",
    },
    OptionSpec {
        flag: "output",
        scope: "run",
        kind: "directory",
        default: None,
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Fresh directory for the scene and the reports",
    },
    OptionSpec {
        flag: "events",
        scope: "run",
        kind: "path",
        default: None,
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Event log to append to (default: events.jsonl in the output directory)",
    },
    OptionSpec {
        flag: "masks",
        scope: "run",
        kind: "provider",
        default: Some("external-sam"),
        choices: &[],
        variable: Some("CRISP3DS_MASKS"),
        repeated: false,
        meaning: "Mask provider: threshold, import:DIR or external-sam",
    },
    OptionSpec {
        flag: "cameras",
        scope: "run",
        kind: "provider",
        default: Some("turntable"),
        choices: &[],
        variable: Some("CRISP3DS_CAMERAS"),
        repeated: false,
        meaning: "Camera provider: turntable, markers, colmap, alicevision or import:PATH",
    },
    OptionSpec {
        flag: "stop-after",
        scope: "run",
        kind: "choice",
        default: None,
        choices: &["masks"],
        variable: None,
        repeated: false,
        meaning: "Write the masks and stop; needs no camera provider",
    },
    OptionSpec {
        flag: "threshold-level",
        scope: "masks:threshold",
        kind: "text",
        default: None,
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Grey level below which a pixel is object: a number or otsu (per photo). Default: otsu for --masks threshold, else 70 (the prompts of external-sam)",
    },
    OptionSpec {
        flag: "threshold-envelope",
        scope: "masks:threshold",
        kind: "text",
        default: Some("auto"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Region the object must lie in: auto (whole frame) or x0,y0,x1,y1 in pixels, fractions if all <= 1",
    },
    OptionSpec {
        flag: "hole-cleanup-budget",
        scope: "masks",
        kind: "number",
        default: Some("0.02"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Largest share of the foreground the dark-hole fill may add, for every mask provider",
    },
    OptionSpec {
        flag: "sam-python",
        scope: "masks:external-sam",
        kind: "executable",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_SAM_PYTHON"),
        repeated: false,
        meaning: "Python interpreter with PyTorch for SAM 2.1",
    },
    OptionSpec {
        flag: "sam-source",
        scope: "masks:external-sam",
        kind: "directory",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_SAM_SOURCE"),
        repeated: false,
        meaning: "Checkout of the SAM 2 source",
    },
    OptionSpec {
        flag: "sam-checkpoint",
        scope: "masks:external-sam",
        kind: "path",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_SAM_CHECKPOINT"),
        repeated: false,
        meaning: "SAM 2.1 checkpoint file",
    },
    OptionSpec {
        flag: "sam-config",
        scope: "masks:external-sam",
        kind: "text",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_SAM_CONFIG"),
        repeated: false,
        meaning: "Name of the SAM model configuration",
    },
    OptionSpec {
        flag: "sam-pythonpath",
        scope: "masks:external-sam",
        kind: "path_list",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_SAM_PYTHONPATH"),
        repeated: false,
        meaning: "Extra module directories for the interpreter, separated like PATH",
    },
    OptionSpec {
        flag: "sam-repository",
        scope: "masks:external-sam",
        kind: "directory",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_REPOSITORY"),
        repeated: false,
        meaning: "Checkout with scripts/turntable_mesh/segment.py",
    },
    OptionSpec {
        flag: "sam-device",
        scope: "masks:external-sam",
        kind: "choice",
        default: Some("mps"),
        choices: &["mps", "cpu", "cuda"],
        variable: None,
        repeated: false,
        meaning: "PyTorch device",
    },
    OptionSpec {
        flag: "sam-multimask",
        scope: "masks:external-sam",
        kind: "switch",
        default: Some("true"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Let SAM propose several masks and take the best",
    },
    OptionSpec {
        flag: "sam-preserve-holes",
        scope: "masks:external-sam",
        kind: "switch",
        default: Some("true"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Keep holes of the prompt mask",
    },
    OptionSpec {
        flag: "sam-automatic-cues",
        scope: "masks:external-sam",
        kind: "switch",
        default: Some("true"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Derive point prompts from the threshold mask",
    },
    OptionSpec {
        flag: "contrast-gamma",
        scope: "cameras",
        kind: "number",
        default: Some("0.5"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Gamma of the images features are detected in; 1 disables",
    },
    OptionSpec {
        flag: "clahe-clip",
        scope: "cameras",
        kind: "number",
        default: Some("2.0"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Clip limit of the local contrast equalisation; 0 disables",
    },
    OptionSpec {
        flag: "clahe-grid",
        scope: "cameras",
        kind: "integer",
        default: Some("8"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Tiles per side of the local contrast equalisation (1 to 64)",
    },
    OptionSpec {
        flag: "random-seed",
        scope: "cameras",
        kind: "integer",
        default: Some("0"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Seed for providers that take one (not COLMAP)",
    },
    OptionSpec {
        flag: "open-turn",
        scope: "cameras",
        kind: "switch",
        default: Some("false"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "The photos do not close a full turn; the closure gate is not applied",
    },
    OptionSpec {
        flag: "alicevision",
        scope: "cameras:alicevision",
        kind: "directory",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_ALICEVISION"),
        repeated: false,
        meaning: "Install prefix with bin/aliceVision_*, or a wrapper script called as `wrapper TOOL args`",
    },
    OptionSpec {
        flag: "alicevision-library-path",
        scope: "cameras:alicevision",
        kind: "path_list",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_ALICEVISION_LIBRARY_PATH"),
        repeated: false,
        meaning: "Extra library directories for a prefix, separated like PATH",
    },
    OptionSpec {
        flag: "alicevision-env",
        scope: "cameras:alicevision",
        kind: "text",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_ALICEVISION_ENV"),
        repeated: true,
        meaning: "Extra variable NAME=VALUE for the tools of a prefix",
    },
    OptionSpec {
        flag: "alicevision-sensor-database",
        scope: "cameras:alicevision",
        kind: "path",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_ALICEVISION_SENSOR_DB"),
        repeated: false,
        meaning: "cameraSensors.db (default: <prefix>/share/aliceVision/)",
    },
    OptionSpec {
        flag: "alicevision-memory-gib",
        scope: "cameras:alicevision",
        kind: "number",
        default: Some("4"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Memory hint passed to the tools",
    },
    OptionSpec {
        flag: "alicevision-initial-field-of-view",
        scope: "cameras:alicevision",
        kind: "number",
        default: Some("45"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Field of view in degrees given to cameraInit",
    },
    OptionSpec {
        flag: "alicevision-describer-types",
        scope: "cameras:alicevision",
        kind: "text",
        default: Some("sift"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Feature describer types",
    },
    OptionSpec {
        flag: "alicevision-describer-preset",
        scope: "cameras:alicevision",
        kind: "text",
        default: Some("normal"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Feature describer preset",
    },
    OptionSpec {
        flag: "alicevision-matching-method",
        scope: "cameras:alicevision",
        kind: "text",
        default: Some("Exhaustive"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Image matching method",
    },
    OptionSpec {
        flag: "alicevision-sfm-option",
        scope: "cameras:alicevision",
        kind: "text",
        default: None,
        choices: &[],
        variable: None,
        repeated: true,
        meaning: "Extra token for globalSfM",
    },
    OptionSpec {
        flag: "colmap",
        scope: "cameras:colmap",
        kind: "executable",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_COLMAP"),
        repeated: false,
        meaning: "The colmap executable, or a wrapper called as `wrapper COMMAND args` (default: colmap on the PATH)",
    },
    OptionSpec {
        flag: "colmap-matching",
        scope: "cameras:colmap",
        kind: "choice",
        default: Some("exhaustive"),
        choices: &["exhaustive", "sequential", "ring"],
        variable: None,
        repeated: false,
        meaning: "Pairs to match: all, ordered neighbours, or ordered neighbours around the closed turn",
    },
    OptionSpec {
        flag: "colmap-overlap",
        scope: "cameras:colmap",
        kind: "integer",
        default: Some("10"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Successors every photo is matched with (sequential and ring)",
    },
    OptionSpec {
        flag: "colmap-masks",
        scope: "cameras:colmap",
        kind: "choice",
        default: Some("on"),
        choices: &["on", "off"],
        variable: None,
        repeated: false,
        meaning: "No features outside the masks",
    },
    OptionSpec {
        flag: "colmap-max-features",
        scope: "cameras:colmap",
        kind: "integer",
        default: Some("8192"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Most features per photo",
    },
    OptionSpec {
        flag: "colmap-cli",
        scope: "cameras:colmap",
        kind: "choice",
        default: Some("auto"),
        choices: &["auto", "3", "4"],
        variable: None,
        repeated: false,
        meaning: "Option names of COLMAP 3 or 4; auto asks the executable for its version",
    },
    OptionSpec {
        flag: "colmap-extractor-option",
        scope: "cameras:colmap",
        kind: "text",
        default: None,
        choices: &[],
        variable: None,
        repeated: true,
        meaning: "Extra token for feature_extractor",
    },
    OptionSpec {
        flag: "colmap-matcher-option",
        scope: "cameras:colmap",
        kind: "text",
        default: None,
        choices: &[],
        variable: None,
        repeated: true,
        meaning: "Extra token for the matcher",
    },
    OptionSpec {
        flag: "colmap-mapper-option",
        scope: "cameras:colmap",
        kind: "text",
        default: None,
        choices: &[],
        variable: None,
        repeated: true,
        meaning: "Extra token for mapper",
    },
    OptionSpec {
        flag: "turntable-features",
        scope: "cameras:turntable",
        kind: "integer",
        default: Some("6000"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Most features kept per photo",
    },
    OptionSpec {
        flag: "turntable-span",
        scope: "cameras:turntable",
        kind: "integer",
        default: Some("4"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Every photo is matched with this many successors",
    },
    OptionSpec {
        flag: "turntable-matches",
        scope: "cameras:turntable",
        kind: "path",
        default: None,
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Matches made elsewhere, in place of the built-in features (development)",
    },
    OptionSpec {
        flag: "markers-mat",
        scope: "cameras:markers",
        kind: "path",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_MARKERS_MAT"),
        repeated: false,
        meaning: "Description of the printed mat, as `crisp3ds-dense mat` writes it",
    },
    OptionSpec {
        flag: "markers-minimum",
        scope: "cameras:markers",
        kind: "integer",
        default: Some("5"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "A photo with fewer decoded markers gets no pose",
    },
    OptionSpec {
        flag: "markers-aspect",
        scope: "cameras:markers",
        kind: "text",
        default: Some("auto"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Height over width of the print relative to the design: auto estimates it, or a number near 1",
    },
    OptionSpec {
        flag: "python",
        scope: "tools",
        kind: "executable",
        default: None,
        choices: &[],
        variable: Some("CRISP3DS_PYTHON"),
        repeated: false,
        meaning: "Interpreter for .py wrappers",
    },
    OptionSpec {
        flag: "threads",
        scope: "machine",
        kind: "integer",
        default: Some("2"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Threads for the steps of this program and the external tools (1 to 256)",
    },
    OptionSpec {
        flag: "minimum-free-gib",
        scope: "machine",
        kind: "number",
        default: Some("10"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Free disk space required before every step",
    },
    OptionSpec {
        flag: "keep-intermediates",
        scope: "machine",
        kind: "switch",
        default: Some("false"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Keep photo copies, contrast images, features and matches",
    },
    OptionSpec {
        flag: "sam-timeout",
        scope: "deadlines",
        kind: "integer",
        default: Some("1800"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Seconds for the SAM step",
    },
    OptionSpec {
        flag: "features-timeout",
        scope: "deadlines",
        kind: "integer",
        default: Some("1800"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Seconds for feature extraction",
    },
    OptionSpec {
        flag: "matching-timeout",
        scope: "deadlines",
        kind: "integer",
        default: Some("1800"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Seconds for matching",
    },
    OptionSpec {
        flag: "sfm-timeout",
        scope: "deadlines",
        kind: "integer",
        default: Some("900"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Seconds for the camera solve",
    },
    OptionSpec {
        flag: "small-step-timeout",
        scope: "deadlines",
        kind: "integer",
        default: Some("600"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Seconds for every other external step",
    },
    OptionSpec {
        flag: "minimum-registered-fraction",
        scope: "gates",
        kind: "number",
        default: Some("0.8"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Smallest share of photos with a pose",
    },
    OptionSpec {
        flag: "minimum-observations-per-view",
        scope: "gates",
        kind: "integer",
        default: Some("20"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Fewest sparse points a registered photo must see",
    },
    OptionSpec {
        flag: "maximum-view-reprojection-p95",
        scope: "gates",
        kind: "number",
        default: Some("4.0"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Largest 95th percentile of a photo's reprojection error, pixels",
    },
    OptionSpec {
        flag: "minimum-positive-depth-fraction",
        scope: "gates",
        kind: "number",
        default: Some("0.999"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Smallest share of observations in front of their camera",
    },
    OptionSpec {
        flag: "maximum-radius-spread-percent",
        scope: "gates",
        kind: "number",
        default: Some("5"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Largest spread of the cameras' distance from the axis",
    },
    OptionSpec {
        flag: "maximum-out-of-plane-percent",
        scope: "gates",
        kind: "number",
        default: Some("5"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Largest departure of the cameras from their common plane",
    },
    OptionSpec {
        flag: "maximum-angular-gap-deg",
        scope: "gates",
        kind: "number",
        default: Some("30"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Largest angle between neighbouring cameras",
    },
    OptionSpec {
        flag: "maximum-reversed-steps",
        scope: "gates",
        kind: "integer",
        default: Some("0"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Most steps against the turning direction",
    },
    OptionSpec {
        flag: "maximum-optical-axis-miss-percent",
        scope: "gates",
        kind: "number",
        default: Some("25"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Farthest an optical axis may pass from the centre",
    },
    OptionSpec {
        flag: "duplicate-step-deg",
        scope: "gates",
        kind: "number",
        default: Some("0.5"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Steps smaller than this are reported as duplicates (warning only)",
    },
    OptionSpec {
        flag: "maximum-closing-step-ratio",
        scope: "gates",
        kind: "number",
        default: Some("2.5"),
        choices: &[],
        variable: None,
        repeated: false,
        meaning: "Unless --open-turn: what is left from the last photo to the first, over the median step",
    },
];

pub fn find(flag: &str) -> Option<&'static OptionSpec> {
    OPTIONS.iter().find(|option| option.flag == flag)
}

/// The default of an option that has one. Panics for a flag the table does not hold with a default: a programming error.
pub fn default(flag: &str) -> &'static str {
    find(flag).and_then(|option| option.default).unwrap_or_else(|| panic!("no default for --{flag} in the option table"))
}

fn row(option: &OptionSpec) -> Value {
    let (module, provider) = match option.scope.split_once(':') {
        Some((module, provider)) => (module, Some(provider)),
        None => (option.scope, None),
    };
    let default = match (option.kind, option.default) {
        ("switch", Some(value)) => json!(value == "true"),
        ("integer", Some(value)) => value.parse::<i64>().map(|v| json!(v)).unwrap_or(json!(value)),
        ("number", Some(value)) => value.parse::<f64>().map(|v| json!(v)).unwrap_or(json!(value)),
        (_, Some(value)) => json!(value),
        (_, None) => Value::Null,
    };
    json!({
        "name": option.flag, "flag": format!("--{}", option.flag), "group": module, "provider": provider, "kind": option.kind,
        "default": default, "choices": option.choices, "variable": option.variable, "repeated": option.repeated,
        "meaning": option.meaning,
    })
}

/// Every option as JSON, in the order of the table.
pub fn listing() -> Value {
    json!({"schema": "crisp3ds_photo_options_v1", "options": OPTIONS.iter().map(row).collect::<Vec<_>>()})
}

/// The options of one provider (`module` is `masks` or `cameras`), as JSON rows.
pub fn of_provider(module: &str, provider: &str) -> Vec<Value> {
    let scope = format!("{module}:{provider}");
    OPTIONS.iter().filter(|option| option.scope == scope).map(row).collect()
}

/// The options of a group that belong to no single provider (`masks`, `cameras`, `tools`, `machine`, `deadlines`, `gates`).
pub fn of_group(group: &str) -> Vec<Value> {
    OPTIONS.iter().filter(|option| option.scope == group).map(row).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_consistent() {
        let kinds = ["switch", "integer", "number", "text", "choice", "provider", "path", "directory", "executable", "path_list"];
        let groups = ["run", "masks", "cameras", "tools", "machine", "deadlines", "gates"];
        for (n, option) in OPTIONS.iter().enumerate() {
            assert!(kinds.contains(&option.kind), "{}", option.flag);
            assert!(groups.contains(&option.scope.split(':').next().unwrap()), "{}", option.flag);
            assert!(OPTIONS[..n].iter().all(|other| other.flag != option.flag), "--{} twice", option.flag);
            assert!(!option.meaning.is_empty() && !option.flag.starts_with("no-"));
            if let Some(provider) = option.scope.split_once(':') {
                assert!(
                    super::super::providers::PROVIDERS.iter().any(|p| (p.module, p.name) == provider),
                    "--{}: no provider {provider:?}",
                    option.flag
                );
            }
            match (option.kind, option.default) {
                ("switch", default) => assert!(matches!(default, Some("true" | "false")), "{}", option.flag),
                ("choice", Some(default)) => assert!(option.choices.contains(&default), "{}", option.flag),
                ("integer", Some(default)) => assert!(default.parse::<i64>().is_ok(), "{}", option.flag),
                ("number", Some(default)) => assert!(default.parse::<f64>().is_ok(), "{}", option.flag),
                _ => {}
            }
            assert_eq!(option.kind == "choice", !option.choices.is_empty(), "{}", option.flag);
        }
        let rows = listing();
        assert_eq!(rows["options"].as_array().unwrap().len(), OPTIONS.len());
        let colmap = of_provider("cameras", "colmap");
        assert_eq!(colmap[0]["flag"], "--colmap");
        assert_eq!((colmap[0]["kind"].as_str(), colmap[0]["variable"].as_str()), (Some("executable"), Some("CRISP3DS_COLMAP")));
        assert_eq!(colmap.iter().find(|row| row["name"] == "colmap-overlap").unwrap()["default"], 10);
        assert_eq!(of_group("cameras").iter().find(|row| row["name"] == "open-turn").unwrap()["default"], false);
        assert!(of_provider("masks", "import").is_empty());
    }
}
