"""Read-only post-run checks for the pinned OpenMVG v2.1 Sceaux photo control.

The cereal sfm_data.bin is sealed but not parsed. This validates its companion
OpenMVG PLY and HTML report, which expose a narrower subset of the model.
"""

from __future__ import annotations

import argparse
import hashlib
from html.parser import HTMLParser
import json
import math
from pathlib import Path
import re
import struct


NAMES = tuple(f"{i:05}.jpg" for i in range(11))
DEFAULT_OUTPUT = Path("/Volumes/backups/code/crisp3ds-data/openmvg-sceaux-photo-sfm-002")
REPORT = "sparse/SfMReconstruction_Report.html"
PLY = "sparse/cloud_and_poses.ply"
MODEL = "sparse/sfm_data.bin"
REPORT_LIMIT = 16 << 20
PLY_LIMIT = 128 << 20
PLY_VERTEX = struct.Struct("<dddBBB")
HEADER = ("ply", "format binary_little_endian 1.0", "comment generated by OpenMVG")
COLORS = {(0, 255, 0): "camera_centers", (255, 255, 255): "landmarks",
          (0, 0, 255): "pose_priors", (255, 0, 0): "control_points"}


def sha256(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as stream:
        for part in iter(lambda: stream.read(1 << 20), b""):
            hasher.update(part)
    return hasher.hexdigest()


class Tables(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.rows = []
        self.row = None
        self.cell = None

    def handle_starttag(self, tag, attrs):
        if tag == "tr":
            self.row = []
        elif tag == "td" and self.row is not None:
            self.cell = []

    def handle_data(self, data):
        if self.cell is not None:
            self.cell.append(data)

    def handle_endtag(self, tag):
        if tag == "td" and self.cell is not None:
            self.row.append("".join(self.cell).strip())
            self.cell = None
        elif tag == "tr" and self.row is not None:
            self.rows.append(self.row)
            self.row = None


def parse_report(path: Path, names: tuple[str, ...] = NAMES) -> dict:
    if path.is_symlink() or not path.is_file() or not (0 < path.stat().st_size <= REPORT_LIMIT):
        raise ValueError("missing, linked, empty, or oversized SfM report")
    html = path.read_text(encoding="utf-8", errors="replace")
    counts = {}
    for key in ("views", "poses", "intrinsics", "tracks", "residuals"):
        hits = re.findall(r"#" + key + r":\s*(\d+)\s*<br\s*/?>", html)
        if len(hits) != 1:
            raise ValueError(f"SfM report lacks unique #{key}")
        counts[key] = int(hits[0])
    tables = Tables()
    tables.feed(html)
    header = ["IdView", "Basename", "#Observations", "Residuals min",
              "Residuals median", "Residuals mean", "Residuals max"]
    positions = [i for i, row in enumerate(tables.rows) if row == header]
    if len(positions) != 1:
        raise ValueError("SfM report lacks unique pinned per-view table")
    per_view = []
    for row in tables.rows[positions[0] + 1: positions[0] + 1 + len(names)]:
        if len(row) != 7:
            raise ValueError("unposed or observation-free view in SfM report")
        try:
            view_id = int(row[0])
            observations = int(row[2])
            residuals = [float(value) for value in row[3:]]
        except ValueError as exc:
            raise ValueError("malformed per-view SfM report value") from exc
        if view_id < 0 or observations <= 0 or any(not math.isfinite(x) or x < 0 for x in residuals):
            raise ValueError("nonpositive observations or nonfinite/negative residual")
        # A distribution's median can be above or below its mean.
        if not (residuals[0] <= residuals[1] <= residuals[3] and
                residuals[0] <= residuals[2] <= residuals[3]):
            raise ValueError("inconsistent per-view residual range")
        per_view.append({"id": view_id, "name": row[1], "observations": observations,
                         "min_px": residuals[0], "median_px": residuals[1],
                         "mean_px": residuals[2], "max_px": residuals[3]})
    rmse_hits = re.findall(r"SfM Scene RMSE:\s*([+\-\d.eE]+)", html)
    if len(rmse_hits) != 1:
        raise ValueError("SfM report lacks unique scene RMSE")
    rmse = float(rmse_hits[0])
    if not math.isfinite(rmse) or rmse < 0:
        raise ValueError("nonfinite/negative scene RMSE")
    if (counts["views"] != len(names) or counts["poses"] != len(names) or
            counts["intrinsics"] <= 0 or counts["tracks"] <= 0 or
            counts["residuals"] <= 0 or len(per_view) != len(names) or
            {v["name"] for v in per_view} != set(names) or
            len({v["id"] for v in per_view}) != len(names) or
            sum(v["observations"] for v in per_view) != counts["residuals"]):
        raise ValueError("SfM report coverage/counts inconsistent")
    return {"counts": counts, "per_view": per_view, "scene_rmse_px_per_axis": rmse,
            "max_view_median_px_per_axis": max(v["median_px"] for v in per_view)}


def parse_ply(path: Path) -> dict:
    if path.is_symlink() or not path.is_file() or not (0 < path.stat().st_size <= PLY_LIMIT):
        raise ValueError("missing, linked, empty, or oversized OpenMVG PLY")
    with path.open("rb") as stream:
        lines = []
        while True:
            line = stream.readline(256)
            if not line or len(line) > 255 or len(lines) > 12:
                raise ValueError("malformed or oversized OpenMVG PLY header")
            lines.append(line.decode("ascii", errors="strict").strip())
            if lines[-1] == "end_header":
                break
        if tuple(lines[:3]) != HEADER:
            raise ValueError("PLY is not pinned OpenMVG binary output")
        count_line = [line for line in lines if line.startswith("element vertex ")]
        if len(count_line) != 1:
            raise ValueError("PLY lacks unique vertex count")
        count = int(count_line[0].removeprefix("element vertex "))
        if count <= 0 or lines[4:] != ["property double x", "property double y", "property double z",
                                      "property uchar red", "property uchar green", "property uchar blue",
                                      "end_header"]:
            raise ValueError("PLY fields differ from pinned OpenMVG writer")
        if path.stat().st_size - stream.tell() != count * PLY_VERTEX.size:
            raise ValueError("PLY payload size differs from header")
        colors = {label: 0 for label in COLORS.values()}
        min_xyz = [math.inf] * 3
        max_xyz = [-math.inf] * 3
        for _ in range(count):
            x, y, z, red, green, blue = PLY_VERTEX.unpack(stream.read(PLY_VERTEX.size))
            if not all(math.isfinite(v) for v in (x, y, z)):
                raise ValueError("PLY has nonfinite camera/landmark coordinate")
            label = COLORS.get((red, green, blue))
            if label is None:
                raise ValueError("PLY has unexpected vertex color")
            colors[label] += 1
            for axis, value in enumerate((x, y, z)):
                min_xyz[axis] = min(min_xyz[axis], value)
                max_xyz[axis] = max(max_xyz[axis], value)
    return {"vertices": count, "colors": colors, "aabb_min": min_xyz, "aabb_max": max_xyz}


def validate(output: Path, names: tuple[str, ...] = NAMES,
             *, expected_root: Path = DEFAULT_OUTPUT) -> dict:
    """Validate only completed, receipt-sealed outputs; never modify them."""
    if output.resolve() != expected_root.resolve():
        raise ValueError("postcheck accepts only the reviewed -002 output root")
    receipt_path = output / "receipt.json"
    if (output.is_symlink() or not output.is_dir() or receipt_path.is_symlink() or
            not receipt_path.is_file() or receipt_path.stat().st_size > REPORT_LIMIT):
        raise ValueError("missing, linked, or oversized photo-control receipt")
    receipt_hash = sha256(receipt_path)
    receipt = json.loads(receipt_path.read_text())
    if (receipt.get("schema") != "openmvg_sceaux_photo_control_v2" or
            receipt.get("status") != "completed_pending_geometry_review" or
            receipt.get("output") != str(output.resolve()) or
            [s.get("name") for s in receipt.get("stages", [])] !=
            ["listing", "features", "putative", "geometric", "sfm"] or
            any(s.get("status") != "completed" for s in receipt["stages"])):
        raise ValueError("photo-control run is not complete and sealed")
    inventory = receipt.get("output_inventory", {})
    hashes = {}
    for relative in (REPORT, PLY, MODEL):
        path = output / relative
        row = inventory.get(relative)
        if (path.is_symlink() or not path.is_file() or not isinstance(row, dict) or
                path.stat().st_size != row.get("bytes") or sha256(path) != row.get("sha256")):
            raise ValueError(f"photo-control artifact seal differs: {relative}")
        hashes[relative] = row["sha256"]
    if receipt["stages"][-1].get("artifact_sha256") != hashes[MODEL]:
        raise ValueError("SfM stage model hash differs from receipt")
    report = parse_report(output / REPORT, names)
    if receipt.get("sfm_report") != report["counts"]:
        raise ValueError("SfM report counts differ from supervisor receipt")
    ply = parse_ply(output / PLY)
    if (ply["colors"]["camera_centers"] != report["counts"]["poses"] or
            ply["colors"]["landmarks"] != report["counts"]["tracks"] or
            ply["colors"]["pose_priors"] or ply["colors"]["control_points"]):
        raise ValueError("PLY camera/track counts differ from report or contain priors/GCP")
    for relative, digest in hashes.items():
        if sha256(output / relative) != digest:
            raise ValueError(f"photo-control artifact changed during validation: {relative}")
    if sha256(receipt_path) != receipt_hash:
        raise ValueError("photo-control receipt changed during validation")
    return {"schema": "openmvg_sceaux_postcheck_v1", "status": "validated_partial_model",
            "artifact_sha256": hashes, "report": report, "ply": ply,
            "reprojection_quality_4px": (report["scene_rmse_px_per_axis"] <= 4.0 and
                                        report["max_view_median_px_per_axis"] <= 4.0),
            "unverified": ["cereal model intrinsics/rotations/track membership",
                           "independently recomputed reprojections", "reference/camera agreement"]}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    print(json.dumps(validate(args.output), sort_keys=True))


if __name__ == "__main__":
    main()
