import json
import math
from pathlib import Path
import tempfile
import unittest

from scripts.classical_backend import openmvg_mustard_sparse_diagnostic as diagnostic
from scripts.classical_backend import openmvg_sceaux_postcheck as shared


class MustardSparseTests(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.output = Path(temp.name)
        (self.output / "sparse").mkdir()
        self.names = tuple(f"NP3_{angle:03d}.jpg" for angle in range(0, 360, 6)
                           if angle % 30 != 24)
        self.missing = {"NP3_042.jpg", "NP3_048.jpg"}
        self.ordered = tuple(reversed(self.names))  # Match pinned unordered-map row order, not angle order.
        self.write_report()
        self.write_ply()
        (self.output / shared.MODEL).write_bytes(b"synthetic opaque cereal")
        self.write_receipt()

    def write_report(self, *, extra_missing=()):
        missing = self.missing | set(extra_missing)
        rows = []
        for i, name in enumerate(self.ordered):
            first = f"<tr><td>{47 - i}</td><td>{Path(name).stem}</td>"
            rows.append(first + ("</tr>" if name in missing else
                                 "<td>3</td><td>0.1</td><td>0.5</td><td>0.7</td><td>2.0</td></tr>"))
        observed = 48 - len(missing)
        html = (f"#views: 48<br> #poses: 46<br> #intrinsics: 1<br> #tracks: 2<br> "
                f"#residuals: {3 * observed}<br>"
                "<table><tr><td>IdView</td><td>Basename</td><td>#Observations</td>"
                "<td>Residuals min</td><td>Residuals median</td><td>Residuals mean</td>"
                "<td>Residuals max</td></tr>" + "".join(rows) + "</table>"
                "SfM Scene RMSE: 0.9<hr>")
        (self.output / shared.REPORT).write_text(html)
        return 3 * observed

    def write_ply(self, *, interleave_white=False):
        centers = []
        for name in self.ordered:
            if name not in self.missing:
                angle = math.radians(int(name[4:7]))
                centers.append((math.cos(angle), math.sin(angle), 0.2, 0, 255, 0))
        white = [(0.0, 0.0, 0.0, 255, 255, 255), (0.1, 0.0, 0.0, 255, 255, 255)]
        points = centers + white
        if interleave_white:
            points = [centers[0], white[0]] + centers[1:] + white[1:]
        header = ("ply\nformat binary_little_endian 1.0\ncomment generated by OpenMVG\n"
                  f"element vertex {len(points)}\nproperty double x\nproperty double y\n"
                  "property double z\nproperty uchar red\nproperty uchar green\n"
                  "property uchar blue\nend_header\n").encode()
        (self.output / shared.PLY).write_bytes(header + b"".join(shared.PLY_VERTEX.pack(*p) for p in points))

    def write_receipt(self, *, residuals=138):
        inventory = {}
        for relative in (shared.REPORT, shared.PLY, shared.MODEL):
            path = self.output / relative
            inventory[relative] = {"bytes": path.stat().st_size, "sha256": shared.sha256(path)}
        receipt = {"schema": diagnostic.SCHEMA, "status": "failed_registration_or_sparse_gate",
                   "output": str(self.output.resolve()),
                   "photos": {"names": self.names,
                              "train_names_sha256": diagnostic.TRAIN_NAMES_SHA,
                              "stage_report_sha256": diagnostic.STAGE_REPORT_SHA},
                   "stages": [{"name": name, "status": "completed"} for name in diagnostic.STAGES],
                   "sfm_report": {"views": 48, "poses": 46, "intrinsics": 1,
                                  "tracks": 2, "residuals": residuals},
                   "output_inventory": inventory}
        receipt["stages"][-1]["artifact_sha256"] = inventory[shared.MODEL]["sha256"]
        (self.output / "receipt.json").write_text(json.dumps(receipt))

    def diagnose(self):
        return diagnostic.diagnose(self.output, expected_root=self.output)

    def test_source_order_mapping_recovers_ideal_full_turn(self):
        result = self.diagnose()
        self.assertEqual(result["status"], "partial_sparse_diagnostic")
        self.assertEqual(result["orbit"]["status"], "provisional_source_order")
        self.assertEqual(result["missing_names"], ["NP3_048.jpg", "NP3_042.jpg"])
        self.assertEqual(result["orbit"]["max_registered_angular_gap_deg"], 24)
        self.assertAlmostEqual(result["orbit"]["six_degree_chord_over_opposing"],
                               math.sin(math.radians(3)), places=6)
        self.assertTrue(all(result["orbit"]["diagnostic_flags"].values()))

    def test_ambiguous_observed_rows_abstain_from_orbit(self):
        residuals = self.write_report(extra_missing={"NP3_060.jpg"})
        self.write_receipt(residuals=residuals)
        result = self.diagnose()
        self.assertEqual(result["orbit"]["status"], "abstained")
        self.assertEqual(result["counts"]["poses"], 46)
        self.assertEqual(result["missing_names"], ["NP3_060.jpg", "NP3_048.jpg", "NP3_042.jpg"])

    def test_shuffled_ply_camera_block_fails_closed(self):
        self.write_ply(interleave_white=True)
        self.write_receipt()
        with self.assertRaisesRegex(ValueError, "block order"):
            self.diagnose()

    def test_duplicate_report_name_and_nonfinite_center_rejected(self):
        path = self.output / shared.REPORT
        path.write_text(path.read_text().replace("<td>NP3_348</td>", "<td>NP3_342</td>", 1))
        self.write_receipt()
        with self.assertRaisesRegex(ValueError, "coverage/counts"):
            self.diagnose()
        self.write_report()
        path = self.output / shared.PLY
        blob = bytearray(path.read_bytes())
        header_end = blob.index(b"end_header\n") + len(b"end_header\n")
        blob[header_end:header_end + 8] = shared.struct.pack("<d", math.nan)
        path.write_bytes(blob)
        self.write_receipt()
        with self.assertRaisesRegex(ValueError, "nonfinite"):
            self.diagnose()


if __name__ == "__main__":
    unittest.main()
