import json
import math
from pathlib import Path
import tempfile
import unittest

from scripts.classical_backend import openmvg_sceaux_postcheck as check


class PostcheckTests(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.output = Path(temp.name)
        (self.output / "sparse").mkdir()
        self.names = check.NAMES
        self.write_report()
        self.write_ply()
        (self.output / check.MODEL).write_bytes(b"opaque cereal fixture")
        self.write_receipt()

    def write_report(self, *, observations=3, rmse=1.25, names=None):
        names = self.names if names is None else names
        rows = "".join(f"<tr><td>{i}</td><td>{Path(name).stem}</td><td>{observations}</td>"
                       "<td>0.1</td><td>0.8</td><td>1.0</td><td>2.5</td></tr>"
                       for i, name in enumerate(names))
        html = (f"#views: 11<br> #poses: 11<br> #intrinsics: 1<br> #tracks: 1<br> "
                f"#residuals: {observations * len(names)}<br>"
                "<table border=\"1\"><tr><td>IdView</td><td>Basename</td>"
                "<td>#Observations</td><td>Residuals min</td><td>Residuals median</td>"
                "<td>Residuals mean</td><td>Residuals max</td></tr>"
                + rows + "</table><hr>SfM Scene RMSE: " + str(rmse) + "<hr>")
        (self.output / check.REPORT).write_text(html)

    def write_ply(self, *, bad_coordinate=False, extra_white=False):
        points = [(float(i), 0.0, 1.0, 0, 255, 0) for i in range(11)]
        points.append((math.nan if bad_coordinate else 1.0, 2.0, 3.0, 255, 255, 255))
        if extra_white:
            points.append((4.0, 5.0, 6.0, 255, 255, 255))
        header = ("ply\nformat binary_little_endian 1.0\ncomment generated by OpenMVG\n"
                  f"element vertex {len(points)}\nproperty double x\nproperty double y\n"
                  "property double z\nproperty uchar red\nproperty uchar green\n"
                  "property uchar blue\nend_header\n").encode()
        (self.output / check.PLY).write_bytes(header + b"".join(check.PLY_VERTEX.pack(*p) for p in points))

    def write_receipt(self, *, status="completed_pending_geometry_review"):
        inventory = {}
        for relative in (check.REPORT, check.PLY, check.MODEL):
            path = self.output / relative
            inventory[relative] = {"bytes": path.stat().st_size, "sha256": check.sha256(path)}
        receipt = {"schema": "openmvg_sceaux_photo_control_v2", "status": status,
                   "output": str(self.output.resolve()),
                   "sfm_report": {"views": 11, "poses": 11, "intrinsics": 1,
                                  "tracks": 1, "residuals": 3 * len(self.names)},
                   "stages": [{"name": name, "status": "completed"} for name in
                              ("listing", "features", "putative", "geometric", "sfm")],
                   "output_inventory": inventory}
        receipt["stages"][-1]["artifact_sha256"] = inventory[check.MODEL]["sha256"]
        (self.output / "receipt.json").write_text(json.dumps(receipt))

    def test_healthy_partial_validation_counts_and_reprojection(self):
        result = check.validate(self.output, expected_root=self.output)
        self.assertEqual(result["status"], "validated_partial_model")
        self.assertEqual(result["ply"]["colors"]["camera_centers"], 11)
        self.assertEqual(result["ply"]["colors"]["landmarks"], 1)
        self.assertEqual(result["report"]["counts"]["residuals"], 33)
        self.assertEqual(result["report"]["per_view"][10]["name"], "00010.jpg")
        self.assertEqual(result["report"]["per_view"][10]["reported_basename"], "00010")
        self.assertTrue(result["reprojection_quality_4px"])
        self.assertIn("cereal model intrinsics/rotations/track membership", result["unverified"])

    def test_nonfinite_ply_and_count_mismatch_rejected(self):
        self.write_ply(bad_coordinate=True)
        self.write_receipt()
        with self.assertRaisesRegex(ValueError, "nonfinite"):
            check.validate(self.output, expected_root=self.output)
        self.write_ply(extra_white=True)
        self.write_receipt()
        with self.assertRaisesRegex(ValueError, "counts differ"):
            check.validate(self.output, expected_root=self.output)

    def test_missing_view_and_empty_observation_rejected(self):
        self.write_report(names=self.names[:-1])
        self.write_receipt()
        with self.assertRaisesRegex(ValueError, "coverage/counts"):
            check.validate(self.output, expected_root=self.output)
        self.write_report(observations=0)
        self.write_receipt()
        with self.assertRaisesRegex(ValueError, "nonpositive observations"):
            check.validate(self.output, expected_root=self.output)

    def test_global_residual_count_is_observations_not_components(self):
        report_path = self.output / check.REPORT
        report_path.write_text(report_path.read_text().replace("#residuals: 33", "#residuals: 66"))
        with self.assertRaisesRegex(ValueError, "coverage/counts"):
            check.parse_report(report_path)

    def test_duplicate_or_malformed_report_stems_fail_closed(self):
        self.write_report(names=(self.names[0],) * len(self.names))
        with self.assertRaisesRegex(ValueError, "coverage/counts"):
            check.parse_report(self.output / check.REPORT)
        self.write_report()
        report_path = self.output / check.REPORT
        report_path.write_text(report_path.read_text().replace("<td>00010</td>",
                                                               "<td>00010.jpg</td>", 1))
        with self.assertRaisesRegex(ValueError, "malformed image basename"):
            check.parse_report(report_path)

    def test_incomplete_receipt_and_changed_artifact_rejected(self):
        self.write_receipt(status="stopped")
        with self.assertRaisesRegex(ValueError, "not complete"):
            check.validate(self.output, expected_root=self.output)
        self.write_receipt()
        with (self.output / check.MODEL).open("ab") as stream:
            stream.write(b"changed")
        with self.assertRaisesRegex(ValueError, "seal differs"):
            check.validate(self.output, expected_root=self.output)

    def test_reprojection_flag_is_diagnostic(self):
        self.write_report(rmse=4.5)
        self.write_receipt()
        result = check.validate(self.output, expected_root=self.output)
        self.assertFalse(result["reprojection_quality_4px"])

    def test_only_v2_receipt_at_expected_root_is_accepted(self):
        receipt_path = self.output / "receipt.json"
        receipt = json.loads(receipt_path.read_text())
        receipt["schema"] = "openmvg_sceaux_photo_control_v1"
        receipt_path.write_text(json.dumps(receipt))
        with self.assertRaisesRegex(ValueError, "not complete"):
            check.validate(self.output, expected_root=self.output)
        with self.assertRaisesRegex(ValueError, "reviewed -002"):
            check.validate(self.output)


if __name__ == "__main__":
    unittest.main()
